pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t johnad186/example-webserver:$DRONE_COMMIT_SHA .
  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run johnad186/example-webserver:$DRONE_COMMIT_SHA /test.sh
  push:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PASS=${HUB_PASS}
    commands:
      - docker login -u johnad186 -p $PASS
      - docker push johnad186/example-webserver:$DRONE_COMMIT_SHA
  deploy:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker pull johnad186/example-webserver:$DRONE_COMMIT_SHA
      - docker tag johnad186/example-webserver:$DRONE_COMMIT_SHA johnad186/example-webserver:latest